# Generated by Django 3.0 on 2022-04-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0002_remove_blog_slug_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-publish_date',)},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-comment_date',)},
        ),
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(default='some_value'),
        ),
    ]
